/*
 *  UCF COP3330 Fall 2021 Assignment 4 Solutions
 *  Copyright 2021 first_name last_name
 */

@startuml
'https://plantuml.com/class-diagram

WebsiteGenerator o-- Solution43

class Solution43 {
    'Creates WebsiteGenerator object and calls methods in class

    askForWebsiteInfo()

    createWebsiteFolder()
    createHtml()

    createJavaScriptFolder()
    createJavaScriptFolder()

    createCssFolder()
}

class WebsiteGenerator {
    - input: Scanner
    - websiteName: String
    - authorName: String
    - mainFolderPath: String
    - websiteFolderPath: String
    - creationPhrase: String
    - includeJavaScriptFolder: boolean
    - includeCssFolder: boolean

    + WebsiteGenerator()
        'Initializes fields to "" and main folder path to "data/"

    + askForWebsiteInfo(): void
    + setAuthorName(String): void

    + setWebsiteName(String): void
    + createWebsiteFolder(): String

    + createHtml(): String
    + createJavaScriptFolder(): String

    + createCssFolder(): String
}

@enduml