/*
 *  UCF COP3330 Fall 2021 Assignment 4 Solutions
 *  Copyright 2021 first_name last_name
 */

@startuml
'https://plantuml.com/class-diagram

WordCounter o-- Solution46

class Solution46 {
    readInFile()
    sortMap()
    outputWordFrequency()
}

class WordCounter {
    - wordFrequency: Map<String, Integer>

    + readInFile(String): void
    - updateWordFrequency(String): void
    + sortMap(): Map<String, Integer>
    + outputWordFrequency(Map<String, Integer>, String): void
}

@enduml