/*
 *  UCF COP3330 Fall 2021 Assignment 4 Solutions
 *  Copyright 2021 first_name last_name
 */

@startuml
'https://plantuml.com/sequence-diagram

NameSorter o-- Solution41

class Solution41 {
    + main()
        'Creates NameSorter object and uses it to manage names
}

class NameSorter {
    - file: File
    - numPeople: int
    - people: ArrayList<String>

    + NameSorter()
        'Initializes the amount of people to 0

    + readFile(): void
    + getPeople(): ArrayList<String>

    + sortNames(ArrayList<String>): void
    + outputSortedNames(ArrayList<String>): void
}

@enduml