/*
 *  UCF COP3330 Fall 2021 Assignment 4 Solutions
 *  Copyright 2021 first_name last_name
 */

@startuml
'https://plantuml.com/class-diagram

WordReplacer o--Solution45

class Solution45 {
    - input: Scanner

    'Create WordReplacer object to call methods

    readInputFile()
    replaceWord()
    outputFile()
}

class WordReplacer {
    - originalText: StringBuilder

    + readInputFile(String): void
    + getOriginalText(): StringBuilder

    + replaceWord(): String
    + outputFile(String, String): void
}

@enduml